# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employeemanagerapp
#server.port=8002
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
